import { Inter } from "next/font/google";
import "./globals.css";
import ProviderRegistery from "@/theme/ProviderRegistery";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={inter.className}>
          <ProviderRegistery>{children}</ProviderRegistery>
        </body>
      </html>
    </SessionProvider>
  );
}
